[package]
name = "FeOS"
version = "0.1.0"
authors = ["kjain1810 <kunaljain.2000@yahoo.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
